- name : Configure Docker on EC2 Instances
  hosts : all
  connection : ssh
  tasks : ]
  - name: Stop a container
  docker_container:
    name: pathakvicky/asi_insurance:latest
    state: stopped
  - name: remove container
  docker_container:
    name: pathakvicky/asi_insurance:latest
    state: absent
  - name: Deploy Docker Container
    command: docker run -itd -p 8084:8081 asi_insurance:latest
